name: master-prod

services:
  nginx:
    image: nginx:1.27.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
  server:
#    image: ghcr.io/$GITHUB_NAMESPACE/server:latest
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    deploy:
      mode: replicated
      replicas: 2
    env_file:
      - .env
  worker:
#    image: ghcr.io/$GITHUB_NAMESPACE/server:latest
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    deploy:
      mode: replicated
      replicas: 3
    env_file:
      - .env
