name: master

services:
  server:
    image: ghcr.io/$GITHUB_NAMESPACE/server:latest
#    build:
#      context: .
#      dockerfile: docker/server.Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
  worker:
    image: ghcr.io/$GITHUB_NAMESPACE/server:latest
#    build:
#      context: .
#      dockerfile: docker/worker.Dockerfile
    deploy:
      mode: replicated
      replicas: 3
    env_file:
      - .env
