name: master

services:
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    deploy:
      mode: replicated
      replicas: 3
    env_file:
      - .env
