name: master

services:
  db:
    container_name: master-db
    image: postgres:16.4
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: master
      POSTGRES_DB: master
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgresql:/custom/mount:/var/lib/postgresql/data"
  storage:
    container_name: master-storage
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    command: [ "server", "/data", "--console-address", ":9001"]
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./data/minio:/data"
